baseURL = "https://timothycline.github.io/ClineLabWebsite/"
# If you later set up a custom domain (e.g. clinelab.montana.edu), update this line.

languageCode = "en"
defaultContentLanguage = "en"
title = "Fisheries Ecology at MSU — Cline Lab"

enableRobotsTXT = true
paginate = 10

[module]
  [[module.imports]]
    path = "github.com/nunocoracao/blowfish/v2"
