[[main]]
  name = "Home"
  url = "/"
  weight = 5

[[main]]
  name = "Research"
  url = "/research/"
  weight = 10

[[main]]
  name = "People"
  url = "/people/"
  weight = 20

[[main]]
  name = "Publications"
  url = "/publications/"
  weight = 30

[[main]]
  name = "News"
  url = "/news/"
  weight = 50
